services:
  postgres:
    container_name: postgres_rentik
    image: postgres
    environment:
      POSTGRES_USER: rentik
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: rentik_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5434:5432
    networks:
      - spring-dev
    restart: unless-stopped
  mail-dev:
    container_name: maildev_rentik
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-dev:
    driver: bridge


volumes:
  postgres:
    driver: local